options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

steps:
  # Create Artifact Registry repository if it doesn't exist
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud artifacts repositories create infis-repo \
          --repository-format=docker \
          --location=us-central1 \
          --description="Docker repository for Events Handler Service" \
          || true

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/infis-repo/events-handler:$BUILD_ID'
      - '.'

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/infis-repo/events-handler:$BUILD_ID']

  # Deploy with service account (no credential files needed!)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'events-handler'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/infis-repo/events-handler:$BUILD_ID'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--port=8080'
      - '--service-account=pub-sub-trigger@infis-ai.iam.gserviceaccount.com'
      - '--vpc-egress=private-ranges-only'
      - '--clear-vpc-connector'
      - '--timeout=300'
      - '--set-env-vars=GOOGLE_CLOUD_PROJECT=$PROJECT_ID,SLACK_REPLY_EVENT_TOPIC=prod_slack_event,EMAIL_REPLIES_TOPIC=email-replies,EMAIL_REPLY_TOPIC=prod_email_reply,DEBUG=false,APP_NAME=Events Handler API,APP_VERSION=1.0.0,PUBSUB_TIMEOUT=60.0,MAX_MESSAGES_PER_PULL=100,API_V1_PREFIX=/api/v1,ALLOWED_HOSTS_RAW=*'
      - '--update-secrets=:GMAIL_OAUTH_TOKEN=GMAIL_OAUTH_TOKEN:latest,GMAIL_CLIENT_SECRET=GMAIL_CLIENT_SECRET:latest'
      - '--execution-environment=gen2'
      - '--cpu-boost'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/infis-repo/events-handler:$BUILD_ID'

timeout: '2800s'  # 30 minutes